services:
  minecraft-server-query:
    build: .
    image: minecraft-server-query:latest
    container_name: minecraft-server-query
    env_file:
      - .env
    volumes:
      - ${HOSTER_BRANCH_PATH}:${HOSTER_BRANCH_PATH}:ro # comment this line out if HOSTER_BRANCH_PATH is not set
      - ${SERVER_MODS_PATH}:${SERVER_MODS_PATH}:ro # comment this line out if SERVER_MODS_PATH is not set
      - ./src:/app/src:ro
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    entrypoint: deno run main